DROP DATABASE IF EXISTS iaspel;
CREATE DATABASE iaspel CHARACTER SET = 'utf8';
USE iaspel;

DROP TABLE IF EXISTS KUSM09T;
DROP TABLE IF EXISTS KUSM01T;
DROP TABLE IF EXISTS KUSM00T;
DROP TABLE IF EXISTS KSAE10T;

CREATE TABLE KUSM00T (
    idusucon INT AUTO_INCREMENT,
    dsusucon VARCHAR(12) NOT NULL,
    dsvalcon VARCHAR(65) NOT NULL,
    instatus VARCHAR(1) NOT NULL,
    tmstmp   DATETIME NOT NULL,
    PRIMARY KEY(idusucon)
);

CREATE UNIQUE INDEX USUARIO_CUENTA ON KUSM00T(dsusucon);

CREATE TABLE KUSM01T (
    idusudet INT AUTO_INCREMENT,
    dsusunom VARCHAR(30) NOT NULL,
    dsusuape VARCHAR(65) NOT null,
    dsusuasp VARCHAR(32) NOT NULL,
    idusuari INT NOT NULL,
    tmstmp   DATETIME NOT NULL,
    PRIMARY KEY(idusudet)
);

CREATE UNIQUE INDEX USUARIO_DETALLE ON KUSM01T(idusuari);
ALTER TABLE KUSM01T ADD CONSTRAINT USUARIO_USUARIO_DETALLE FOREIGN KEY(idusuari)
      REFERENCES KUSM00T(idusucon)
      ON DELETE CASCADE
      ON UPDATE CASCADE;

CREATE TABLE KUSM09T (
    idnumses INT AUTO_INCREMENT,    
    dstoken  VARCHAR(32) NOT NULL,
    dtfecini DATETIME NOT NULL,
    dtfecfin DATETIME NOT NULL,
    instatus VARCHAR(1) NOT NULL,
    idusuari INT NOT NULL,
    tmstmp   DATETIME NOT NULL,
    PRIMARY KEY(idnumses),
    FOREIGN KEY(idusuari)
	REFERENCES KUSM00T(idusucon)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE KSAE10T (
    idnummov INT AUTO_INCREMENT,
    cddocume VARCHAR(15) NOT NULL,
    cddocpar INT NOT NULL,
    dbimport DOUBLE NOT NULL,
    instatus VARCHAR(1) NOT NULL,
    idnumcoi VARCHAR(32) NULL,
    idusuari INT NOT NULL,
    tmstmp DATETIME NOT NULL,
    PRIMARY KEY(idnummov),
    FOREIGN KEY(idusuari)
      REFERENCES KUSM00T(idusucon)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);