-- MySQL Script generated by MySQL Workbench
-- Sat Apr 12 20:06:58 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`FlujoTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FlujoTrabajo` (
  `identificador` VARCHAR(32) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `version` INT NOT NULL,
  `publicado` CHAR(1) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL COMMENT 'Identifica un elemento del tipo Workflow que es el contenedor de los procesos.',
  PRIMARY KEY (`identificador`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `IDXVERSION` ON `mydb`.`FlujoTrabajo` (`version` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proceso` (
  `identificador` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL COMMENT 'Elemento que concentra las transiciones entre actividades.',
  `archivo` VARCHAR(120) NULL,
  `idsesion` VARCHAR(45) NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  PRIMARY KEY (`identificador`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `mydb`.`Proceso` (`nombre` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`FlujoProcesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FlujoProcesos` (
  `idflijo` VARCHAR(32) NOT NULL,
  `idproceso` VARCHAR(32) NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  PRIMARY KEY (`idflijo`, `idproceso`),
  CONSTRAINT `FLUJOTRABAJO`
    FOREIGN KEY (`idflijo`)
    REFERENCES `mydb`.`FlujoTrabajo` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROCESO`
    FOREIGN KEY (`idproceso`)
    REFERENCES `mydb`.`Proceso` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `PROCESO_idx` ON `mydb`.`FlujoProcesos` (`idproceso` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Transicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transicion` (
  `identificador` VARCHAR(32) NOT NULL,
  `idactividad` VARCHAR(32) NOT NULL,
  `tipodestino` VARCHAR(2) NULL,
  `tmstmp` DATETIME NULL,
  `idsesion` VARCHAR(32) NULL,
  PRIMARY KEY (`identificador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `identificador` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(120) NOT NULL,
  `tipoAccion` VARCHAR(2) NOT NULL,
  `tiempostd` INT NULL,
  `tiempolmt` INT NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`identificador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransicionDestino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransicionDestino` (
  `identificador` VARCHAR(32) NOT NULL,
  `idtransicion` VARCHAR(45) NOT NULL,
  `idactividad` VARCHAR(32) NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`identificador`),
  CONSTRAINT `ACTIVIDAD`
    FOREIGN KEY (`idactividad`)
    REFERENCES `mydb`.`Actividad` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TRANSICION`
    FOREIGN KEY (`idtransicion`)
    REFERENCES `mydb`.`Transicion` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ACTIVIDAD_idx` ON `mydb`.`TransicionDestino` (`idactividad` ASC);

CREATE INDEX `TRANSICION_idx` ON `mydb`.`TransicionDestino` (`idtransicion` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ProcesoTransiciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProcesoTransiciones` (
  `idproceso` VARCHAR(32) NOT NULL,
  `idtransicion` VARCHAR(32) NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idproceso`, `idtransicion`),
  CONSTRAINT `TRANSICION`
    FOREIGN KEY (`idtransicion`)
    REFERENCES `mydb`.`Transicion` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROCESO`
    FOREIGN KEY (`idproceso`)
    REFERENCES `mydb`.`Proceso` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `TRANSICION_idx` ON `mydb`.`ProcesoTransiciones` (`idtransicion` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parametro` (
  `identificador` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `tipoDato` VARCHAR(3) NOT NULL,
  `tmstmp` DATETIME NULL,
  `idsesion` VARCHAR(32) NULL,
  PRIMARY KEY (`identificador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ActividadParametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ActividadParametros` (
  `idactividad` VARCHAR(32) NOT NULL,
  `idparametro` VARCHAR(32) NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idactividad`, `idparametro`),
  CONSTRAINT `ACTIVIDAD`
    FOREIGN KEY (`idactividad`)
    REFERENCES `mydb`.`Actividad` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PARAMETRO`
    FOREIGN KEY (`idparametro`)
    REFERENCES `mydb`.`Parametro` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `PARAMETRO_idx` ON `mydb`.`ActividadParametros` (`idparametro` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TransicionDestionoParametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransicionDestionoParametro` (
  `idetransicion` VARCHAR(32) NOT NULL,
  `idparametro` VARCHAR(32) NOT NULL,
  `tmstmp` DATETIME NULL,
  `idsesion` VARCHAR(32) NULL,
  PRIMARY KEY (`idetransicion`, `idparametro`),
  CONSTRAINT `TRANSICION`
    FOREIGN KEY (`idetransicion`)
    REFERENCES `mydb`.`TransicionDestino` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PARAMETRO`
    FOREIGN KEY (`idparametro`)
    REFERENCES `mydb`.`Parametro` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `PARAMETRO_idx` ON `mydb`.`TransicionDestionoParametro` (`idparametro` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `identificador` VARCHAR(32) NOT NULL,
  `idrol` VARCHAR(32) NOT NULL,
  `prefijo` VARCHAR(5) NOT NULL,
  `descripcion` VARCHAR(120) NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`identificador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ActividadRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ActividadRoles` (
  `idactividad` VARCHAR(32) NOT NULL,
  `idrol` VARCHAR(32) NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idactividad`, `idrol`),
  CONSTRAINT `ACTIVIDAD`
    FOREIGN KEY (`idactividad`)
    REFERENCES `mydb`.`Actividad` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ROL`
    FOREIGN KEY (`idrol`)
    REFERENCES `mydb`.`Rol` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ROL_idx` ON `mydb`.`ActividadRoles` (`idrol` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `identificador` VARCHAR(32) NOT NULL,
  `idusuario` VARCHAR(16) NULL,
  `nombre` VARCHAR(120) NULL,
  `idrol` VARCHAR(32) NULL,
  `tmstmp` DATETIME NULL,
  `idsesion` VARCHAR(32) NULL,
  PRIMARY KEY (`identificador`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idusuario_UNIQUE` ON `mydb`.`Usuario` (`idusuario` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ActividadUsusarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ActividadUsusarios` (
  `idactividad` VARCHAR(32) NOT NULL,
  `idusuario` VARCHAR(32) NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idactividad`, `idusuario`),
  CONSTRAINT `ACTIVIDAD`
    FOREIGN KEY (`idactividad`)
    REFERENCES `mydb`.`Actividad` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `USUARIO`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`Usuario` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `USUARIO_idx` ON `mydb`.`ActividadUsusarios` (`idusuario` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Tramite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tramite` (
  `identificador` VARCHAR(32) NOT NULL,
  `idtramite` VARCHAR(32) NOT NULL,
  `idflujo` VARCHAR(32) NOT NULL,
  `idusuario` VARCHAR(32) NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  `status` VARCHAR(2) NOT NULL,
  `tmstmp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identificador`),
  CONSTRAINT `FLUJOTRABAJO`
    FOREIGN KEY (`idflujo`)
    REFERENCES `mydb`.`FlujoTrabajo` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FLUJOTRABAJO_idx` ON `mydb`.`Tramite` (`idflujo` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarea` (
  `identificador` VARCHAR(32) NOT NULL,
  `idtramite` VARCHAR(32) NOT NULL,
  `idactividad` VARCHAR(3) NOT NULL,
  `status` VARCHAR(2) NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`identificador`),
  CONSTRAINT `TRAMITE`
    FOREIGN KEY (`idtramite`)
    REFERENCES `mydb`.`Tramite` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ACTIVIDAD`
    FOREIGN KEY (`idactividad`)
    REFERENCES `mydb`.`Actividad` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `TRAMITE_idx` ON `mydb`.`Tarea` (`idtramite` ASC);

CREATE INDEX `ACTIVIDAD_idx` ON `mydb`.`Tarea` (`idactividad` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TareaParamteros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TareaParamteros` (
  `idtarea` VARCHAR(32) NOT NULL,
  `idparametro` VARCHAR(32) NOT NULL,
  `valparametro` VARCHAR(255) NOT NULL,
  `tmstmp` DATETIME NOT NULL,
  `idsesion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idtarea`, `idparametro`),
  CONSTRAINT `TAREA`
    FOREIGN KEY (`idtarea`)
    REFERENCES `mydb`.`Tarea` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PARAMETRO`
    FOREIGN KEY (`idparametro`)
    REFERENCES `mydb`.`Parametro` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `PARAMETRO_idx` ON `mydb`.`TareaParamteros` (`idparametro` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `identificador` VARCHAR(32) NOT NULL,
  `idtarea` VARCHAR(32) NULL,
  `idusuario` VARCHAR(32) NULL,
  `fecha` DATETIME NULL,
  `comentario` VARCHAR(500) NULL,
  `tmstmp` DATETIME NULL,
  `idsesion` VARCHAR(32) NULL,
  PRIMARY KEY (`identificador`),
  CONSTRAINT `TAREA`
    FOREIGN KEY (`idtarea`)
    REFERENCES `mydb`.`Tarea` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `TAREA_idx` ON `mydb`.`Comentario` (`idtarea` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
